/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "幸福的丹丹",
  "description": "My personal blog",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/images/wd-img.jpg"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/images/wd-img.jpg",
        "actionText": "进入主页 →",
        "actionLink": "/javaScript/dataStructure/dataStructure/",
        "features": [
          {
            "title": "个人简介",
            "details": "90后 前端攻城狮一枚"
          },
          {
            "title": "兴趣爱好",
            "details": "旅游，爬山，看电影，打球..."
          },
          {
            "title": "名言",
            "details": "我不是一个伟大的程序员，我只是一个具有良好习惯的优秀程序员。"
          }
        ],
        "footer": "My Blog | Copyright © 2019-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-397e4a80",
      "path": "/"
    },
    {
      "title": "Javascript数据结构",
      "frontmatter": {},
      "regularPath": "/javaScript/dataStructure/dataStructure.html",
      "relativePath": "javaScript/dataStructure/dataStructure.md",
      "key": "v-e937dc6a",
      "path": "/javaScript/dataStructure/dataStructure.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "​简介",
          "slug": "​简介"
        },
        {
          "level": 2,
          "title": "正文",
          "slug": "正文"
        },
        {
          "level": 3,
          "title": "数组",
          "slug": "数组"
        },
        {
          "level": 3,
          "title": "Stack（栈）",
          "slug": "stack-栈"
        },
        {
          "level": 3,
          "title": "Queue（队列）",
          "slug": "queue-队列"
        },
        {
          "level": 3,
          "title": "Linked List（链表）",
          "slug": "linked-list-链表"
        },
        {
          "level": 3,
          "title": "Set（集合）",
          "slug": "set-集合"
        },
        {
          "level": 3,
          "title": "Dictionary （字典）",
          "slug": "dictionary-字典"
        },
        {
          "level": 3,
          "title": "Hash Table（哈希表/散列表）",
          "slug": "hash-table-哈希表-散列表"
        },
        {
          "level": 3,
          "title": "Tree （树）",
          "slug": "tree-树"
        },
        {
          "level": 3,
          "title": "Graph（图）",
          "slug": "graph-图"
        },
        {
          "level": 2,
          "title": "致谢",
          "slug": "致谢"
        }
      ]
    }
  ],
  "themeConfig": {
    "lastUpdated": "上次更新时间",
    "sidebarDepth": 2,
    "logo": "/images/wd-img.jpg",
    "smoothScroll": true,
    "nav": [
      {
        "text": "首页",
        "link": "/index/"
      },
      {
        "text": "数据结构",
        "link": "/javaScript/dataStructure/dataStructure"
      }
    ],
    "sidebar": {
      "/javaScript/dataStructure/": [
        "dataStructure"
      ]
    }
  }
}